# For local development, you can use the following docker-compose.yml file:
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    ports:
      - 5432:5432

  cache:
    image: redis:6
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    # Build from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Or use the latest version available on Docker Hub.
    # image: directus/directus:11
    pull_policy: always
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./templates:/directus/templates
      - ./scripts:/directus/scripts
      - ./snapshots:/directus/snapshots
      - ./migrations:/directus/migrations
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      KEY: ${KEY}
      SECRET: ${SECRET}

      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      CACHE_ENABLED: "true"
      CACHE_AUTO_PURGE: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      STORAGE_S3_DRIVER: ${STORAGE_S3_DRIVER}
      STORAGE_S3_KEY: ${STORAGE_S3_KEY}
      STORAGE_S3_SECRET: ${STORAGE_S3_SECRET}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_BUCKET: ${STORAGE_S3_BUCKET}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}

      CORS_ENABLED: ${CORS_ENABLED}
      CORS_ORIGIN: ${CORS_ORIGIN}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      CORS_EXPOSED_HEADERS: ${CORS_EXPOSED_HEADERS}
      CORS_METHODS: ${CORS_METHODS}

      EXTENSIONS_PATH: ${EXTENSIONS_PATH}
      EMAIL_TEMPLATES_PATH: ${EMAIL_TEMPLATES_PATH}
      MIGRATIONS_PATH: ${MIGRATIONS_PATH}
      CACHE_TTL: ${CACHE_TTL}
      CACHE_CONTROL_S_MAXAGE: ${CACHE_CONTROL_S_MAXAGE}
      ASSETS_TRANSFORM_MAX_CONCURRENT: ${ASSETS_TRANSFORM_MAX_CONCURRENT}
      ASSETS_TRANSFORM_MAX_OPERATIONS: ${ASSETS_TRANSFORM_MAX_OPERATIONS}
      RATE_LIMITER_ENABLED: ${RATE_LIMITER_ENABLED}
      RATE_LIMITER_POINTS: ${RATE_LIMITER_POINTS}
      RATE_LIMITER_DURATION: ${RATE_LIMITER_DURATION}
      RATE_LIMITER_STORE: ${RATE_LIMITER_STORE}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
      REFRESH_TOKEN_COOKIE_SECURE: ${REFRESH_TOKEN_COOKIE_SECURE}
      REFRESH_TOKEN_COOKIE_SAME_SITE: ${REFRESH_TOKEN_COOKIE_SAME_SITE}
      SESSION_COOKIE_TTL: ${SESSION_COOKIE_TTL}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE}
      SESSION_COOKIE_SAME_SITE: ${SESSION_COOKIE_SAME_SITE}
      USER_REGISTER_URL_ALLOW_LIST: ${USER_REGISTER_URL_ALLOW_LIST}
      EMAIL_TRANSPORT: ${EMAIL_TRANSPORT}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      EMAIL_SMTP_SECURE: ${EMAIL_SMTP_SECURE}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USER}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}

      WEBSOCKETS_ENABLED: "true"
      EXTENSIONS_AUTO_RELOAD: "true"

      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)
      # PUBLIC_URL: "https://directus.example.com"
