name: test Website
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
      
      - name: Install Dependencies
        shell: bash
        run: |
          pnpm install
      
      - name: Build and Launch Website
        shell: bash
        env:
          MOLLIE_API_KEY: ${{ secrets.MOLLIE_API_KEY }}
          WIX_API_KEY: ${{ secrets.WIX_API_KEY }}
        run: |
          cd apps/website
          npm run build && npm run launch
